$mainMod = SUPER
$terminal = alacritty
$fileManager = nautilus
$browser = google-chrome-stable

monitor = , preferred, auto, 1

exec-once = qs
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = /usr/lib/polkit-kde-authentication-agent-1

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland;xcb

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(7aa2f7ee) rgba(bb9af7ee) 45deg
    col.inactive_border = rgba(414868aa)
    layout = dwindle
}

decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 0.94
    blur {
        enabled = true
        size = 6
        passes = 2
    }
}

animations {
    enabled = true
    bezier = smooth, 0.25, 0.1, 0.25, 1.0
    animation = windows, 1, 5, smooth
    animation = workspaces, 1, 5, smooth
}

dwindle {
    pseudotile = true
    preserve_split = true
}

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, B, exec, $browser
bind = $mainMod, E, exec, code
bind = $mainMod, G, exec, code --new-window
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, Q, killactive
bind = $mainMod SHIFT, M, exit
bind = $mainMod, V, togglefloating
bind = $mainMod, SPACE, exec, alacritty -e bash -lc 'compgen -c | sort -u | fzf | xargs -r uwsm app --'

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

windowrule = suppressevent maximize, class:.*
